### PR TITLE
feat: make aaptPath nullable

### PR DESCRIPTION
**Pull request by Canny1913**

### CODE REVIEW

**Review by oSumAtrIX — APPROVED** [review]

**Comment by oSumAtrIX** [comment]
Iirc you need to bump the version as well for a successfull release.

**Comment by Canny1913** [comment]
Ah so it doesn't autobump

**Comment by Canny1913** [comment]
Done

**Comment by oSumAtrIX** [comment]
A feat bumps minor not patch.

**Comment by Canny1913** [comment]
Done

**Comment by oSumAtrIX** [comment]
No empty string object is allocated by default.

**Pull request merged**
